import React from 'react';
import { X, Sparkles, Loader2, Lightbulb } from 'lucide-react';

interface InsightModalProps {
  isOpen: boolean;
  onClose: () => void;
  isLoading: boolean;
  content: string;
}

const InsightModal: React.FC<InsightModalProps> = ({ isOpen, onClose, isLoading, content }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-slate-900/30 backdrop-blur-sm transition-opacity"
        onClick={onClose}
      />

      {/* Modal Content */}
      <div className="bg-white rounded-3xl shadow-2xl w-full max-w-2xl overflow-hidden relative z-10 animate-in fade-in zoom-in-95 duration-300">
        <div className="bg-gradient-to-r from-emerald-600 to-teal-600 p-6 flex items-center justify-between text-white">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-white/20 rounded-xl backdrop-blur-md">
              <Sparkles size={24} />
            </div>
            <div>
              <h2 className="text-xl font-bold">AI Data Insights</h2>
              <p className="text-emerald-100 text-xs font-medium uppercase tracking-wider">Powered by Gemini</p>
            </div>
          </div>
          <button 
            onClick={onClose}
            className="p-2 hover:bg-white/20 rounded-full transition-colors"
          >
            <X size={20} />
          </button>
        </div>

        <div className="p-8 min-h-[300px] flex flex-col">
          {isLoading ? (
            <div className="flex-grow flex flex-col items-center justify-center text-emerald-600 gap-4 py-12">
              <Loader2 size={48} className="animate-spin" />
              <div className="text-center">
                 <p className="font-bold text-lg animate-pulse">Analyzing Data...</p>
                 <p className="text-sm text-slate-400">Consulting with Gemini AI models</p>
              </div>
            </div>
          ) : (
            <div className="prose prose-emerald prose-sm md:prose-base max-w-none text-slate-600 leading-relaxed">
               {/* Simple formatting for the raw text response */}
               {content.split('\n').map((line, i) => {
                 if (line.trim().startsWith('**') || line.trim().endsWith(':')) {
                    return <h3 key={i} className="text-slate-800 font-bold mt-4 mb-2">{line.replace(/\*\*/g, '')}</h3>
                 } else if (line.trim().startsWith('-') || line.trim().startsWith('•')) {
                    return (
                      <div key={i} className="flex gap-2 mb-2 ml-2">
                        <span className="text-emerald-500 mt-1.5 flex-shrink-0"><div className="w-1.5 h-1.5 rounded-full bg-current"/></span>
                        <span>{line.replace(/^[-\u2022]\s*/, '').replace(/\*\*/g, '')}</span>
                      </div>
                    )
                 } else if (line.trim() === '') {
                    return <br key={i}/>
                 }
                 return <p key={i} className="mb-2">{line.replace(/\*\*/g, '')}</p>
               })}
               
               <div className="mt-8 p-4 bg-yellow-50 border border-yellow-100 rounded-xl flex items-start gap-3">
                  <Lightbulb className="text-yellow-500 flex-shrink-0 mt-0.5" size={20} />
                  <p className="text-xs text-yellow-700 font-medium">
                    This analysis is generated by AI based on the current filtered dataset.
                  </p>
               </div>
            </div>
          )}
        </div>
        
        <div className="p-4 bg-slate-50 border-t border-slate-100 flex justify-end">
          <button 
            onClick={onClose}
            className="px-6 py-2.5 bg-slate-200 hover:bg-slate-300 text-slate-700 font-bold rounded-xl transition-colors text-sm"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};

export default InsightModal;